CREATE TABLE IF NOT EXISTS positions (
 id BIGSERIAL PRIMARY KEY NOT NULL,
 user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
 asset_id BIGINT NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
 quantity DOUBLE PRECISION NOT NULL CHECK (quantity > 0),
 avg_price DOUBLE PRECISION NOT NULL CHECK (avg_price >= 0),
 UNIQUE (user_id, asset_id)
);
